# CMake generated Testfile for 
# Source directory: /home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/examples/energy
# Build directory: /home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/cmake-cache/examples/energy
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-energy-model-example "ns3.40-energy-model-example-default")
set_tests_properties(ctest-energy-model-example PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/examples/energy/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/examples/energy/CMakeLists.txt;1;build_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/examples/energy/CMakeLists.txt;0;")
add_test(ctest-energy-model-with-harvesting-example "ns3.40-energy-model-with-harvesting-example-default")
set_tests_properties(ctest-energy-model-with-harvesting-example PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/examples/energy/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/examples/energy/CMakeLists.txt;13;build_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/examples/energy/CMakeLists.txt;0;")
