# CMake generated Testfile for 
# Source directory: /home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples
# Build directory: /home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/cmake-cache/src/energy/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-generic-battery-discharge-example "ns3.40-generic-battery-discharge-example-default")
set_tests_properties(ctest-generic-battery-discharge-example PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;1;build_lib_example;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-generic-battery-wifiradio-example "ns3.40-generic-battery-wifiradio-example-default")
set_tests_properties(ctest-generic-battery-wifiradio-example PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build/examples//" _BACKTRACE_TRIPLES "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1883;build_exec;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;8;build_example;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-li-ion-energy-source-example "ns3.40-li-ion-energy-source-example-default")
set_tests_properties(ctest-li-ion-energy-source-example PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;20;build_lib_example;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-rv-battery-model-test "ns3.40-rv-battery-model-test-default")
set_tests_properties(ctest-rv-battery-model-test PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;27;build_lib_example;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;0;")
add_test(ctest-basic-energy-model-test "ns3.40-basic-energy-model-test-default")
set_tests_properties(ctest-basic-energy-model-test PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build/src/energy/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;36;build_lib_example;/home/k981c/Desktop/NewFolder/TCP-Congestion-Control-Using-DQN/simulation/ns-allinone-3.40/ns-3.40/src/energy/examples/CMakeLists.txt;0;")
