# CMake generated Testfile for 
# Source directory: /home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples
# Build directory: /home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/cmake-cache/contrib/opengym/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-interference-pattern "ns3.40-interference-pattern-default")
set_tests_properties(ctest-interference-pattern PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/contrib/opengym/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;1;build_lib_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;0;")
add_test(ctest-linear-mesh "ns3.40-linear-mesh-default")
set_tests_properties(ctest-linear-mesh PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/contrib/opengym/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;12;build_lib_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;0;")
add_test(ctest-linear-mesh-2 "ns3.40-linear-mesh-2-default")
set_tests_properties(ctest-linear-mesh-2 PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/contrib/opengym/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;23;build_lib_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;0;")
add_test(ctest-opengym "ns3.40-opengym-default")
set_tests_properties(ctest-opengym PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/contrib/opengym/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;35;build_lib_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;0;")
add_test(ctest-opengym-2 "ns3.40-opengym-2-default")
set_tests_properties(ctest-opengym-2 PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/contrib/opengym/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;43;build_lib_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;0;")
add_test(ctest-rl-tcp "ns3.40-rl-tcp-default")
set_tests_properties(ctest-rl-tcp PROPERTIES  WORKING_DIRECTORY "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build/contrib/opengym/examples/" _BACKTRACE_TRIPLES "/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1655;add_test;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/macros-and-definitions.cmake;1730;set_runtime_outputdirectory;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/build-support/custom-modules/ns3-module-macros.cmake;476;build_exec;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;52;build_lib_example;/home/k981c/Desktop/CongestionControlTCP/ns-allinone-3.40/ns-3.40/contrib/opengym/examples/CMakeLists.txt;0;")
